#!/usr/bin/python3
""" """
from tests.test_models.test_base_model import test_basemodel
from models.place import Place


class test_Place(test_basemodel):
    """ Base class """

    def __init__(self, *args, **kwargs):
        """ instance of the class to test for args"""
        super().__init__(*args, **kwargs)
        self.name = "Place"
        self.value = Place

    def test_city_id(self):
        """ instance of the class to city-id """
        new = self.value()
        self.assertEqual(type(new.city_id), str)

    def test_user_id(self):
        """ instance of the class to test for userid"""
        new = self.value()
        self.assertEqual(type(new.user_id), str)

    def test_name(self):
        """ instance of the class to test for name """
        new = self.value()
        self.assertEqual(type(new.name), str)

    def test_description(self):
        """ instance of the class to test for description """
        new = self.value()
        self.assertEqual(type(new.description), str)

    def test_number_rooms(self):
        """ instance of the class to test for number of rooms """
        new = self.value()
        self.assertEqual(type(new.number_rooms), int)

    def test_number_bathrooms(self):
        """ instance of the class to test for number of bathrooms """
        new = self.value()
        self.assertEqual(type(new.number_bathrooms), int)

    def test_max_guest(self):
        """ instance of the class to test for max guusts """
        new = self.value()
        self.assertEqual(type(new.max_guest), int)

    def test_price_by_night(self):
        """ instance of the class to test for price per night """
        new = self.value()
        self.assertEqual(type(new.price_by_night), int)

    def test_latitude(self):
        """ instance of the class to test for location cordinates """
        new = self.value()
        self.assertEqual(type(new.latitude), float)

    def test_longitude(self):
        """ instance of the class to test for location cordinates """
        new = self.value()
        self.assertEqual(type(new.latitude), float)

    def test_amenity_ids(self):
        """ instance of the class to test for amenity id """
        new = self.value()
        self.assertEqual(type(new.amenity_ids), list)